project_name   = "my-spring-app"
db_name        = "productdb"
db_username    = "admin"
db_password    = "StrongPassword123!"
jwt_secret     = "bXlTM2N1cjNTdXAzckwwbmdKV1RLM3khMjAyNSQlXiYqKCk="
aws_region     = "us-east-1"
